title: My Wrangler Studios Portfolio
description: This is my portfolio showcasing my projects and skills.
baseurl: ""
url: "https://eg1966980.github.io"
theme: jekyll-theme-cayman # replace “merlot” with your chosen theme from the list
